name: build-gmcopilot-container

on:
  workflow_call:
    inputs:
      BUILD_VERSION:
        description: 'The version to assign to the container image'
        required: true
        type: string
      RESOURCE_GROUP_NAME:
        description: 'The name of the resource group where the container registry is located'
        required: true
        type: string
      CONTAINER_REGISTRY_NAME:
        description: 'The name of the container registry'
        required: true
        type: string
    secrets:
      AZURE_TENANT_ID:
        description: 'The Azure tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'The Azure subscription ID'
        required: true
      AZURE_CLIENT_ID:
        description: 'The Azure client ID'
        required: true
  
jobs:
  build-gmcopilot-container:
    name: Build and publish GM Copilot container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Build and push image to ACR      
        run: az acr build --image gmcopilot/gmcopilot:${{ inputs.BUILD_VERSION }} --registry ${{ inputs.CONTAINER_REGISTRY_NAME }} -g ${{ inputs.RESOURCE_GROUP_NAME }} --target final -f ./src/GMCopilot/GMCopilot/GMCopilot/Dockerfile .
