name: build-armtemplates

on:
  workflow_call:

jobs:
  build-armtemplates:
    name: Build ARM Templates from Bicep
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Bicep
      run: | 
        curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
        chmod +x ./bicepinstall
        sudo mv ./bicepinstall /usr/local/bin/bicep
        bicep --help
     
    - name: Build Shared Bicep
      run: |
        bicep build ./infrastructure/bicep/shared.bicep

    - name: Upload Shared ARM Template as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: sharedarmtemplate
        path: ./infrastructure/bicep/shared.json

    - name: Build Application Bicep
      run: |
        bicep build ./infrastructure/bicep/application.bicep
  
    - name: Upload Application ARM Template as workflow artifact
      uses: actions/upload-artifact@v3
      with:
        name: applicationarmtemplate
        path: ./infrastructure/bicep/application.json