name: continuous-integration

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  test-run-unit-tests:
    uses: ./.github/workflows/test-run-unit-tests.yml

  build-application-client:
    needs:
      - test-run-unit-tests
    uses: ./.github/workflows/build-application-client.yml
    with:
      BUILD_CONFIGURATION: Debug
    
  build-arm-templates:
    uses: ./.github/workflows/build-arm-templates.yml