name: continuous-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  # We are building an ARM template rather than submitting the Bicep directly
  # because this allows us to use the latest version of the Bicep compiler.

  build-armtemplate:
    uses: ./.github/workflows/build-armtemplate.yml

  validate-infrastructure:
    needs:
      - build-armtemplate
    uses: ./.github/workflows/validate-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
      AZUREAD_INSTANCE: ${{ vars.AZUREAD_INSTANCE }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZUREAD_DOMAIN: ${{ secrets.AZUREAD_DOMAIN }}
      AZUREAD_TENANT_ID: ${{ secrets.AZUREAD_TENANT_ID }}
      AZUREAD_CLIENT_ID: ${{ secrets.AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENTSECRET: ${{ secrets.AZUREAD_CLIENTSECRET }}
  
  deploy-infrastructure:
    needs:
      - validate-infrastructure
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
      AZUREAD_INSTANCE: ${{ vars.AZUREAD_INSTANCE }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZUREAD_DOMAIN: ${{ secrets.AZUREAD_DOMAIN }}
      AZUREAD_TENANT_ID: ${{ secrets.AZUREAD_TENANT_ID }}
      AZUREAD_CLIENT_ID: ${{ secrets.AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENTSECRET: ${{ secrets.AZUREAD_CLIENTSECRET }}

  test-gmcopilot:
    uses: ./.github/workflows/test-gmcopilot.yml

  build-gmcopilot:
    needs:
      - test-gmcopilot
    uses: ./.github/workflows/build-gmcopilot.yml
  
  build-gmcopilot-container:
    needs:
      - deploy-infrastructure
    uses: ./.github/workflows/build-gmcopilot-container.yml
    with:
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      CONTAINER_REGISTRY_NAME: ${{ needs.deploy-infrastructure.outputs.containerRegistryName }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    
  publish-gmcopilot:
    needs:
      - build-gmcopilot
      - deploy-infrastructure
    uses: ./.github/workflows/publish-gmcopilot.yml
    with:
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      WEBAPPNAME: ${{ needs.deploy-infrastructure.outputs.WebAppName }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    