name: continuous-integration

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  test-gmcopilot:
    uses: ./.github/workflows/test-gmcopilot.yml

  build-gmcopilot:
    needs:
      - test-gmcopilot
    uses: ./.github/workflows/build-gmcopilot.yml
    
  build-armtemplates:
    uses: ./.github/workflows/build-armtemplates.yml