name: continuous-deployment

on:
  push:
    branches:
      - main
    tags:
      - v*

  workflow_dispatch:
  
env:
  BUILD_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref || github.sha }}
    
permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  test-gmcopilot:
    uses: ./.github/workflows/test-gmcopilot.yml

  build-armtemplates:
    uses: ./.github/workflows/build-armtemplates.yml

  validate-shared-infrastructure:
    needs:
      - set-build-variables
      - build-armtemplates
    uses: ./.github/workflows/validate-shared-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME_SHARED: ${{ vars.BASE_RESOURCE_NAME_SHARED }}
      RESOURCE_GROUP_NAME_SHARED: ${{ vars.RESOURCE_GROUP_NAME_SHARED }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  deploy-shared-infrastructure:
    needs:
      - set-build-variables
      - validate-shared-infrastructure
    uses: ./.github/workflows/deploy-shared-infrastructure.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME_SHARED: ${{ vars.BASE_RESOURCE_NAME_SHARED }}
      RESOURCE_GROUP_NAME_SHARED: ${{ vars.RESOURCE_GROUP_NAME_SHARED }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  
  build-gmcopilot-container:
    needs:
      - set-build-variables
      - deploy-shared-infrastructure
      - test-gmcopilot
    uses: ./.github/workflows/build-gmcopilot-container.yml
    with:
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME_SHARED }}
      CONTAINER_REGISTRY_NAME: ${{ needs.deploy-shared-infrastructure.outputs.containerRegistryName }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      
  validate-application-infrastructure-test:
    needs:
      - set-build-variables
      - build-gmcopilot-container
    uses: ./.github/workflows/validate-application-infrastructure.yml
    with:
      ENVIRONMENT: Test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      LOCATION: ${{ vars.LOCATION }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
      AZUREAD_INSTANCE: ${{ vars.AZUREAD_INSTANCE }}
      RESOURCE_GROUP_NAME_SHARED: ${{ vars.RESOURCE_GROUP_NAME_SHARED }}
      BASE_RESOURCE_NAME_SHARED: ${{ vars.BASE_RESOURCE_NAME_SHARED }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZUREAD_DOMAIN: ${{ secrets.AZUREAD_DOMAIN }}
      AZUREAD_TENANT_ID: ${{ secrets.AZUREAD_TENANT_ID }}
      AZUREAD_CLIENT_ID: ${{ secrets.AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENTSECRET: ${{ secrets.AZUREAD_CLIENTSECRET }}
  
  deploy-application-infrastructure-test:
    needs:
      - set-build-variables
      - validate-application-infrastructure-test
    uses: ./.github/workflows/deploy-application-infrastructure.yml
    with:
      ENVIRONMENT: Test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      LOCATION: ${{ vars.LOCATION }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
      AZUREAD_INSTANCE: ${{ vars.AZUREAD_INSTANCE }}
      RESOURCE_GROUP_NAME_SHARED: ${{ vars.RESOURCE_GROUP_NAME_SHARED }}
      BASE_RESOURCE_NAME_SHARED: ${{ vars.BASE_RESOURCE_NAME_SHARED }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZUREAD_DOMAIN: ${{ secrets.AZUREAD_DOMAIN }}
      AZUREAD_TENANT_ID: ${{ secrets.AZUREAD_TENANT_ID }}
      AZUREAD_CLIENT_ID: ${{ secrets.AZUREAD_CLIENT_ID }}
      AZUREAD_CLIENTSECRET: ${{ secrets.AZUREAD_CLIENTSECRET }}
