name: deploy-application-client

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to validate the application infrastructure for"
        required: true
        type: string
      STATIC_WEB_APP_NAME:
        description: 'The name of the static web app to deploy the client to'
        required: true
        type: string
    secrets:
      AZURE_TENANT_ID:
        description: 'The Azure tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'The Azure subscription ID'
        required: true
      AZURE_CLIENT_ID:
        description: 'The Azure client ID'
        required: true
  
jobs:
  build-accessapi-container:
    name: Deploy client to static web app
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }} 

      - name: Update appsettings.json
        run: |
          # Output the current appsettings.json file
          cat src/GMCopilot/GMCopilot/wwwroot/appsettings.json

      - name: Get static web app token
        id: get-static-web-app-token
        run: |
          api_token=$(az staticwebapp secrets list --name ${{ inputs.STATIC_WEB_APP_NAME }} --resource-group ${{ vars.RESOURCE_GROUP_NAME }} | jq -r '.properties.apiKey')
          echo "api_token=$api_token" >> "$GITHUB_OUTPUT"
  
      - name: Build and publish
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get-static-web-app-token.outputs.api_token }}
          action: "upload"
          app_location: "src/GMCopilot/GMCopilot"
          output_location: "wwwroot"
          app_build_command: "dotnet publish -c Release -o bin"
