name: deploy-application-infrastructure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to validate the application infrastructure for"
        required: true
        type: string
      BUILD_VERSION:
        description: "The version of the build to deploy to the application resources"
        required: true
        type: string
      LOCATION:
        description: "The Azure region to deploy the application resources to"
        required: true
        type: string
      RESOURCE_GROUP_NAME_SHARED:
        description: "The name of the resource group that the shared resources are in"
        required: true
        type: string
      BASE_RESOURCE_NAME_SHARED:
        description: "The base name of the shared resources"
        required: true
        type: string
      ENTRAID_AUTHORITY:
        description: "The Entra ID Authority URL to use for authentication"
        required: true
        type: string
      ENTRAID_TENANT_ID:
        description: "The tenant ID of the Entra ID tenant to use for application authentication"
        required: true
        type: string
      ENTRAID_DOMAIN:
        description: "The domain name of the Entra ID tenant"
        required: true
        type: string
      ENTRAID_CLIENT_ID_CLIENT:
        description: "The client ID that the WASM client will used to connect to the Entra ID to perform application authentication"
        required: true
        type: string
      ENTRAID_CLIENT_ID_API:
        description: "The client ID that the APIs will used to connect to the Entra ID to perform application authentication"
        required: true
        type: string
          
    secrets:
      AZURE_TENANT_ID:
        description: "The Azure tenant ID to use for authentication to Azure for deployment"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "The Azure subscription ID to use for authentication to Azure for deployment"
        required: true
      AZURE_CLIENT_ID:
        description: "The Azure client ID to use for authentication to Azure for deployment"
        required: true
  
    outputs:
      staticWebAppName:
        description: "The name of the Static Web Application that the client is deployed to"
        value: ${{ jobs.deploy-application-infrastructure.outputs.staticWebAppName }}
      staticWebAppHostName:
        description: "The host name of the Static Web Application that the client is deployed to"
        value: ${{ jobs.deploy-application-infrastructure.outputs.staticWebAppHostName }}
      containerAppApiUrl:
        description: "The URL of the Access API"
        value: ${{ jobs.deploy-application-infrastructure.outputs.containerAppApiUrl }}

jobs:
  deploy-application-infrastructure:
    name: Deploy Application Infrastructure ${{ inputs.ENVIRONMENT }}
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    outputs:
      staticWebAppName: ${{ steps.deploy.outputs.staticWebAppName }}
      staticWebAppHostName: ${{ steps.deploy.outputs.staticWebAppHostName }}
      containerAppApiUrl: ${{ steps.deploy.outputs.containerAppApiUrl }}

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Deploy Azure resources
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          deploymentName: 'app-${{ inputs.ENVIRONMENT }}-${{ github.action_ref }}-${{ github.run_number }}'
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./applicationarmtemplate/application.json
          region: ${{ inputs.LOCATION }}
          scope: subscription
          parameters: >
            location=${{ inputs.LOCATION }}
            environmentCode=${{ inputs.ENVIRONMENT }}
            baseResourceName=${{ vars.BASE_RESOURCE_NAME }}
            resourceGroupName=${{ vars.RESOURCE_GROUP_NAME }}
            resourceGroupNameShared=${{ inputs.RESOURCE_GROUP_NAME_SHARED }}
            baseResourceNameShared=${{ inputs.BASE_RESOURCE_NAME_SHARED }}
            buildVersion=${{ inputs.BUILD_VERSION }}
            entraIdAuthority=${{ inputs.ENTRAID_AUTHORITY }}
            entraIdTenantId=${{ inputs.ENTRAID_TENANT_ID }}
            entraIdDomain=${{ inputs.ENTRAID_DOMAIN }}
            entraIdClientIdClient=${{ inputs.ENTRAID_CLIENT_ID_CLIENT }}
            entraIdClientIdApi=${{ inputs.ENTRAID_CLIENT_ID_API }}
