name: set-build-variables

on:
  workflow_call:
    outputs:
      BUILD_VERSION:
        description: The build version
        value: ${{ jobs.set-build-variables.outputs.build_version }}

jobs:
  set-build-variables:
    name: Set build variables
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.generate-build-version.outputs.build_version }}
    steps:
      - name: Generate build version
        id: generate-build-version
        run: |
          echo "build_version=${{ startsWith(github.ref, 'refs/tags/') && github.ref || github.sha }}" >> "$GITHUB_ENV"
