name: test-run-unit-tests

on:
  workflow_call:

jobs:
  test-run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Run unit tests on GMCopilot.Core
        run: |
          dotnet test --configuration Release --logger trx
        working-directory: ./src/GMCopilot/Tests/GMCopilot.Core.Test/

      - name: Upload test results for GMCopilot.Core
        uses: actions/upload-artifact@v4
        with:
          name: GMCopilot.Core.Test
          path: ./src/GMCopilot/Tests/GMCopilot.Core.Test/TestResults/*.trx

      - name: Publish test results for GMCopilot.Core
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              ./src/GMCopilot/Tests/GMCopilot.Core.Test/TestResults/*.trx