name: validate-application-infrastructure

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "The environment to validate the application infrastructure for"
        required: true
        type: string
      BUILD_VERSION:
        description: "The version of the build to deploy to the application resources"
        required: true
        type: string
      LOCATION:
        description: "The Azure region to deploy the application resources to"
        required: true
        type: string          
      RESOURCE_GROUP_NAME_SHARED:
        description: "The name of the resource group that the shared resources are in"
        required: true
        type: string
      BASE_RESOURCE_NAME_SHARED:
        description: "The base name of the shared resources"
        required: true
        type: string
      ENTRAID_ISSUER_URL:
        description: "The Entra ID Issuer URL to use for authentication"
        required: true
        type: string
      ENTRAID_TENANT_ID:
        description: "The tenant ID of the Entra ID tenant to use for application authentication"
        required: true
        type: string
      ENTRAID_CLIENT_ID:
        description: "The client ID to use to connect to the Entra ID to perform application authentication"
        required: true
        type: string
          
    secrets:
      AZURE_TENANT_ID:
        description: "The Azure tenant ID to use for authentication to Azure for deployment"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "The Azure subscription ID to use for authentication to Azure for deployment"
        required: true
      AZURE_CLIENT_ID:
        description: "The Azure client ID to use for authentication to Azure for deployment"
        required: true
      ENTRAID_CLIENT_SECRET:
        description: "The client secret to use to connect to the Entra ID to perform application authentication"
        required: true
  
jobs:
  validate-application-infrastructure:
    name: Validate Application Infrastructure ${{ inputs.ENVIRONMENT }}
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Run what-if
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./applicationarmtemplate/application.json
          region: ${{ inputs.LOCATION }}
          scope: subscription
          parameters: >
            location=${{ inputs.LOCATION }}
            baseResourceName=${{ vars.BASE_RESOURCE_NAME }}
            resourceGroupName=${{ vars.RESOURCE_GROUP_NAME }}
            resourceGroupNameShared=${{ inputs.RESOURCE_GROUP_NAME_SHARED }}
            baseResourceNameShared=${{ inputs.BASE_RESOURCE_NAME_SHARED }}
            buildVersion=${{ inputs.BUILD_VERSION }}
            entraIdIssuerUrl=${{ inputs.ENTRAID_ISSUER_URL }}
            entraIdTenantId=${{ inputs.AZUREAD_TENANT_ID }}
            entraIdClientId=${{ inputs.AZUREAD_CLIENT_ID }}
            entraIdClientSecret=${{ secrets.AZUREAD_CLIENT_SECRET }}
          additionalArguments: --what-if