name: validate-application-infrastructure

on:
  workflow_call:
    inputs:
      BUILD_VERSION:
        description: "The version of the build to deploy to the application resources"
        required: true
        type: string
      LOCATION:
        description: "The Azure region to deploy the application resources to"
        required: true
        type: string
      BASE_RESOURCE_NAME:
        description: "The base name of the application resources to deploy"
        required: true
        type: string
      RESOURCE_GROUP_NAME:
        description: "The name of the resource group to deploy the application resources to"
        required: true
        type: string
      APPSERVICEPLAN_CONFIGURATION:
        description: "The configuration of the app service plan to deploy the web app to"
        required: true
        type: string
      AZUREAD_INSTANCE:
        description: "The Azure AD instance to use for authentication"
        required: true
        type: string
    secrets:
      AZURE_TENANT_ID:
        description: "The Azure tenant ID to use for authentication to Azure for deployment"
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: "The Azure subscription ID to use for authentication to Azure for deployment"
        required: true
      AZURE_CLIENT_ID:
        description: "The Azure client ID to use for authentication to Azure for deployment"
        required: true
      AZUREAD_DOMAIN:
        description: "The domain name of the Azure AD tenant to use for application authentication"
        required: true
      AZUREAD_TENANT_ID:
        description: "The tenant ID of the Azure AD tenant to use for application authentication"
        required: true
      AZUREAD_CLIENT_ID:
        description: "The client ID to use to connect to the Azure AD to perform application authentication"
        required: true
      AZUREAD_CLIENTSECRET:
        description: "The client secret to use to connect to the Azure AD to perform application authentication"
        required: true
  
jobs:
  validate-application-infrastructure:
    name: Validate Application Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Run what-if
        uses: azure/arm-deploy@v1
        with:
          failOnStdErr: false
          resourceGroupName: ${{ inputs.RESOURCE_GROUP_NAME }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./applicationarmtemplate/application.json
          region: ${{ inputs.LOCATION }}
          scope: subscription
          parameters: >
            location=${{ inputs.LOCATION }}
            baseResourceName=${{ inputs.BASE_RESOURCE_NAME }}
            resourceGroupName=${{ inputs.RESOURCE_GROUP_NAME }}
            appServicePlanConfiguration=${{ inputs.APPSERVICEPLAN_CONFIGURATION }}
            azureAdInstance=${{ inputs.AZUREAD_INSTANCE }}
            azureAdDomain=${{ secrets.AZUREAD_DOMAIN }}
            azureAdTenantId=${{ secrets.AZUREAD_TENANT_ID }}
            azureAdClientId=${{ secrets.AZUREAD_CLIENT_ID }}
            azureAdClientSecret=${{ secrets.AZUREAD_CLIENTSECRET }}
          additionalArguments: --what-if